"use client";
import { useState } from "react";
import type { MouseEventHandler } from "react";
import Head from "next/head";
import { LazyImage } from "./components/lazyImage";
import type { NextPage } from "next";
import { random } from "lodash";

const randomFox = () => random(1, 123);

//generate function to random id with uuid
const generateUuid = (): string => {
  var dt = new Date().getTime();
  var uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
    var r = (dt + Math.random() * 16) % 16 | 0;
    dt = Math.floor(dt / 16);
    return (c == 'x' ? r : (r & 0x3 | 0x8)).toString(16);
  });
  return uuid;
}

const Home: NextPage = () => {
  const [images, setImages] = useState<Array<IFoxImageItem>>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) => {
    event.preventDefault();
    const newImage: IFoxImageItem = { id: generateUuid(), url: `https://randomfox.ca/images/${randomFox()}.jpg` };
    setImages([...images, newImage]);
  }

  return (
    <div>
      <Head>
        <title>Curso de platzi</title>
        <meta name="description" content="Generated By MateoGonz__" />
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>

        <button onClick={addNewFox} className="btn btn-blue">Add fox!</button>

        {images.map(({ id, url }) => (
          <div key={id} className="p-4">
            <LazyImage
              alt={"foxImage"}
              src={url}
              onLazyLoad={() => console.log('LazyLoaded')}
              onClick={() => console.log('clicked !')} />
          </div>
        ))}
      </main>
    </div>
  )
}

export default Home;