import Head from "next/head";
import { RandomFox } from "./components/randomFox";

const random = (): number => Math.floor(Math.random() * 123) + 1;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Curso de platzi</title>
        <meta name="description" content="Generated By MateoGonz__" />
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <RandomFox alt={"foxImage"} image={`https://randomfox.ca/images/${random()}.jpg`} />
      </main>
    </div>
  )
}
